services:
  whoknows_app:
    image: ghcr.io/martin-s-angels/whoknows_variations_server:latest
    ports:
      - "8080:8080"
    networks:
      - my_network
    volumes:
    - /home/adminuser/env/.env:/who_knows/.dotenv/.env:ro #.env (defined in gh actions) 
    - /home/adminuser/db/whoknows.db:/who_knows/db/whoknows.db #db

  whoknows_nginx:
    image: nginx:latest
    ports:
      - "80:80"
      - "443:443" #https certificate
    depends_on:
      - whoknows_app
    networks:
      - my_network

    volumes:
      - /etc/letsencrypt/live/martins-angels.dk:/etc/letsencrypt/live/martins-angels.dk       #certificates
      - /etc/letsencrypt/archive/martins-angels.dk:/etc/letsencrypt/archive/martins-angels.dk
      - ./network/nginx.conf:/etc/nginx/nginx.conf #nginx.conf

    restart: always

networks:
  my_network:
    driver: bridge
