services:
  whoknows_app:
    image: ghcr.io/martin-s-angels/whoknows_variations_server:latest
    ports:
      - "8080:8080"
    networks:
      - my_network
    volumes:
    - /home/adminuser/env/.env:/who_knows/.dotenv/.env:ro #.env (defined in gh actions) 
    - /home/adminuser/db/whoknows.db:/who_knows/db/whoknows.db #db

  whoknows_nginx:
    image: nginx:latest
    ports:
      - "80:80"
      - "443:443" #https certificate
    depends_on:
      - whoknows_app
    networks:
      - my_network

  volumes:
    - ./network/nginx.conf:/etc/nginx/conf.d/default.conf
    - /etc/letsencrypt:/etc/letsencrypt:ro
  restart: always
  prometheus:
    image: prom/prometheus
    container_name: prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"

  grafana:
    image: grafana/grafana:10.2.4
    ports:
      - "3000:3000"


networks:
  my_network:
    driver: bridge
