services:
  whoknows_app:
    build:
      context: ..
      dockerfile: .devops/Dockerfile.app
    image: whoknows_variations_dev
    ports:
      - "8080:8080"
    volumes:
      - ..:/who_knows  
    networks:
      - my_network

  database:
    build:
      context: ..
      dockerfile: .devops/Dockerfile.database
    env_file:
    - ../.dotenv/.env
    restart: always
    container_name: whoknows_database
    ports:
      - "5432:5432"
    volumes: 
      - database:/var/lib/postgresql
    networks:
      - my_network
    extra_hosts:
      - "host.docker.internal:host-gateway"

  prometheus:
    image: prom/prometheus
    container_name: prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"

  grafana:
    image: grafana/grafana:10.2.4
    ports:
      - "3000:3000"

volumes:
  database:

networks:
  my_network:
    driver: bridge