services:
  whoknows_app:
    image: ghcr.io/martin-s-angels/whoknows_variations_server:latest
    build:
      context: ..
      dockerfile: .devops/Dockerfile.app
    ports:
      - "8080:8080"
    networks:
      - my_network

  whoknows_nginx:
    image: ghcr.io/martin-s-angels/whoknows_variations_nginx:latest
    build:
      context: ..
      dockerfile: .devops/Dockerfile.nginx
    ports:
      - "80:80"
    depends_on:
      - whoknows_app
    networks:
      - my_network
    volumes:
      - ./network/nginx.conf:/etc/nginx/conf.d/default.conf

networks:
  my_network:
    driver: bridge
      