services:
  whoknows_app:
    image: ghcr.io/martin-s-angels/whoknows_variations_server:latest
    build:
      context: ..
      dockerfile: .devops/Dockerfile.app
    ports:
      - "8080:8080"
    networks:
      - my_network

  whoknows_nginx:
    image: nginx:latest
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - whoknows_app
    networks:
      - my_network
    volumes:
      - ./network/nginx.conf:/etc/nginx/conf.d/default.conf
      - /etc/letsencrypt/live/martins-angels.dk:/etc/letsencrypt/live/martins-angels.dk
      - /etc/letsencrypt/archive/martins-angels.dk:/etc/letsencrypt/archive/martins-angels.dk
    restart: always

networks:
  my_network:
    driver: bridge
      