services:
  whoknows_app:
    image: ghcr.io/martin-s-angels/whoknows_variations_server:latest
    ports:
      - "8080:8080"
    networks:
      - my_network
    volumes:
    - /home/adminuser/env/.env:/who_knows/.dotenv/.env:ro #.env (defined in gh actions) 
    - /home/adminuser/db/whoknows.db:/who_knows/db/whoknows.db #db

  whoknows_nginx:
    image: nginx:latest
    ports:
      - "80:80"
      - "443:443" #https certificate
    depends_on:
      - whoknows_app
    networks:
      - my_network
    volumes:
      - ./network/nginx.conf:/etc/nginx/conf.d/default.conf
      - /etc/letsencrypt:/etc/letsencrypt:ro

  restart: always

  database:
    image: ghcr.io/martin-s-angels/whoknows_variations_server:latest
    restart: always
    container_name: whoknows_database
    ports:
      - "5432:5432"
    volumes: 
      - database:/var/lib/postgresql
    networks:
      - my_network
    extra_hosts:
      - "host.docker.internal:host-gateway"
  volumes:
    database:


networks:
  my_network:
    driver: bridge
