services:
  whoknows_flask:
    image: ghcr.io/martin-s-angels/whoknows_variations_server:latest
    ports:
      - "8080:8080"
    networks:
      - my_network
    #volumes:
    #- /home/adminuser/.env:/who_knows/.dotenv:ro #added volume so our docker use the .env that gets uploaded to the server from the workflow. 

  whoknows_nginx:
    image: ghcr.io/martin-s-angels/whoknows_variations_nginx:latest
    ports:
      - "80:80"
    depends_on:
      - whoknows_flask
    networks:
      - my_network

networks:
  my_network:
    driver: bridge
