
#on pullrequest
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  workflow_dispatch:

jobs:
  integration:
    runs-on: ubuntu-latest #build vm
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: bundle install 
        run:  cd who_knows && bundle install 

      - name: use Linter
        run:  rubocop -a
      - name: use check if errors from linter
        run:  rubocop 


#Linter

#Unit test

# build test milj√∏
# integrationstest

