on:
  pull_request:
    types: [closed]
    branches:
      - master

jobs:
  deploy-to-release:
    runs-on: ubuntu-latest

    if: ${{ github.event.pull_request.merged && 
      contains(github.event.pull_request.labels.*.name, 'ready-for-release') }} # release label must be added to PR
      
    steps:
      - name: checkout code
        uses: actions/checkout@v5 

      - name: login to GitHub
        run: |
          echo ${{ secrets.GITHUB_TOKEN }} | gh auth login --with-token

      - name: push to release      
        run: |
          git pull --all 
          git commit -a -m "Merge through GH Actions"
          git push -f origin release-2



  



    


