on:
  push:
    #types: [closed]
    branches:
      - "#63-release-workflow"

jobs:
  deploy-to-release:
    runs-on: ubuntu-latest
<<<<<<< HEAD

    permissions:
      contents: write
#    if: ${{ github.event.pull_request.merged && 
 #     contains(github.event.pull_request.labels.*.name, 'ready-for-release') }} # release label must be added to PR
=======
    
    permissions:
      contents: write
      
    if: ${{ github.event.pull_request.merged == true && 
      contains(github.event.pull_request.labels.*.name, 'ready-for-release') }} # release label must be added to PR
>>>>>>> master
      
    steps:
      - name: checkout code
        uses: actions/checkout@v5 
        with:
          fetch-depth: 0

      - name: login to GitHub
        run: |
          echo ${{ secrets.GITHUB_TOKEN }} | gh auth login --with-token

<<<<<<< HEAD
      - name: Configure Git user
        run: |
          git config user.name "${{ github.actor }}"
          git config user.email "${{ github.actor }}@users.noreply.github.com"

      - name: push to release      
        run: |
          git pull --all 
          git checkout release-2
          git merge origin/master --commit -m "New release"
          git push 



  



    

=======
      - name: Configure Git User
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
      
      - name: push to release
        run: |
          git switch release-2
          git pull origin release-2
          git merge origin/master
          git push origin release-2
>>>>>>> master

