on:
  push:
    branches:
      - master

jobs:
  deploy-to-release:
    runs-on: ubuntu-latest

    steps:
      - name: checkout code
        uses: actions/checkout@v5 

      - name: login to GitHub
        run: |
          echo ${{ secrets.GITHUB_TOKEN }} | gh auth login --with-token

      - name: push to release      
        run: git switch release-2 | git pull | git merge master 


  



    


